lecture-4/hw
moislunaire/react202311 pull request #4
Opened 2023-11-26 14:21 UTC by moislunaire

2023-11-27 12:25 UTC, SArchieEdu requested changes

2023-11-27 12:25 UTC, SArchieEdu commented on src/components/review-form/component.tsx
> +  }, [count]);
перемудрил, тут можно сильно проще, покажу на лекции

2023-11-28 14:51 UTC, moislunaire commented on src/components/review-form/component.tsx
> +  }, [count]);
Так и не поняла, как тут можно сделать проще, если нужно из кастомного хука переменную в форму записать

2023-11-30 13:58 UTC, ArchieSA commented on src/components/review-form/component.tsx
> +  }, [count]);
тут сам кастомный хук лишний, тк стейт и в нем, и в форме. Много дублирования. Лучше отказаться от хука и логика будет сильно проще

2023-12-03 18:07 UTC, moislunaire commented on src/components/review-form/component.tsx
> +  }, [count]);
убрала

2023-12-04 14:28 UTC, SArchieEdu approved these changes

2023-12-04 17:50 UTC, merged